/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.raven.form;

import Controller.IOSystem;
import Controller.MainController;
import Controller.RequestAPI;
import java.io.IOException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
//import java.util.logging.Level;
//import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.SwingWorker;

/**
 *
 * @author RAVEN
 */
public class Form_2 extends javax.swing.JPanel {

    public List<String> getTimeList() {
        return timeList;
    }

    public void setTimeList(List<String> timeList) {
        this.timeList = timeList;
    }

    /**
     * Creates new form Form_1
     */
    private String time = "";
    private List<String> timeList;
    public Form_2() {
        initComponents();
        timeList = new ArrayList<>();
        try {
            time = (String) IOSystem.getInstance().read(MainController.getInstance().getProjectPath()+ "/Files/latestUpdateTime.dat").get(0);
            latestUpdateTimeText.setText(time);
        } catch (IOException ex) {
//            Logger.getLogger(Form_2.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
//            Logger.getLogger(Form_2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnUpdate = new com.raven.swing.Button();
        updateText = new javax.swing.JLabel();
        latestUpdateTimeText = new javax.swing.JLabel();

        btnUpdate.setText("Update class list");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        updateText.setBackground(new java.awt.Color(204, 204, 204));
        updateText.setText("Latest update: ");

        latestUpdateTimeText.setText("latestUpdateTime");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(updateText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(latestUpdateTimeText)
                .addContainerGap(352, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateText)
                    .addComponent(latestUpdateTimeText))
                .addContainerGap(421, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        btnUpdate.setIcon(new ImageIcon(getClass().getResource("/loading1.gif")));
        SwingWorker sw1 = new SwingWorker(){
            @Override
            protected Object doInBackground() throws Exception {
                RequestAPI.getInstance().updateClassList();
                return null;
            }
            @Override
            protected void done(){
                latestUpdateTimeText.setText(time);
                btnUpdate.setIcon(null);
            }
        };
        sw1.execute();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("HH:mm:ss dd-MM-yyyy");
        time = LocalDateTime.now().format(formatter);
        
        timeList.add(time);

        try {
            IOSystem.getInstance().write(timeList, MainController.getInstance().getProjectPath()+ "/Files/latestUpdateTime.dat");
        } catch (IOException ex) {
//            Logger.getLogger(Form_2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.raven.swing.Button btnUpdate;
    private javax.swing.JLabel latestUpdateTimeText;
    private javax.swing.JLabel updateText;
    // End of variables declaration//GEN-END:variables
}
